# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, editable=False)),
                ('tag', models.CharField(max_length=30)),
                ('user', models.CharField(blank=True, max_length=30)),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='updatetime')),
                ('mac', models.CharField(blank=True, max_length=48)),
                ('department', models.CharField(blank=True, max_length=20)),
                ('project', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cpu_vendor', models.CharField(blank=True, max_length=20)),
                ('cpu_cores', models.PositiveIntegerField(default=1, verbose_name='CPU Cores')),
                ('cpu_speed', models.FloatField(default=0, verbose_name='CPU Speed(MHz)')),
                ('cache_size', models.FloatField(default=0, verbose_name='Cache Size(KB)')),
                ('mem_total', models.PositiveIntegerField(default=0, verbose_name='Memory Total(KB)')),
                ('swap_total', models.PositiveIntegerField(default=0, verbose_name='Swap Total(KB)')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('I', 'Input Device'), ('O', 'Monitor Device'), ('P', 'Printer Device'), ('U', 'USB Device')], max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=40)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsApp.Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=40, verbose_name='Name')),
                ('software_version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('software_size', models.FloatField(default=0, verbose_name='Size')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsApp.Terminal')),
            ],
        ),
    ]
