# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('TAR', 'Tar Package'), ('RPM', 'Rpm Package'), ('DEB', 'Deb Package')], default='TAR', max_length=20, verbose_name='type')),
                ('selected', models.BooleanField(default=False, editable=False, verbose_name='To Install?')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='upload time')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='terminaldevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('I', 'Input Device'), ('O', 'Monitor Device'), ('P', 'Printer Device'), ('U', 'USB Device')], max_length=20, null=True),
        ),
    ]
