# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsApp', '0003_auto_20160114_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='terminaldevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='terminalsoftware',
            name='software_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
